### ISSUE TITLE
Simplify definitional test ``get_ibd`` function

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit#1677]
The function ``get_ibd`` in ``tests/ibd.py`` has parameters ``path_ibd`` and ``mrca_ibd`` which I don't think we're using any more, and makes it more difficult to understand what's going on.  I don't think we're going to work with multiple definitions of IBD now, so it would be better to make this function as straightforward and clear as possible.

Probably related: the ``test_sim_wright_fisher_generations`` tests are failing (after #1660 has dropped).

@gtsambos, I think this is one for you?

**Comment by gtsambos** [comment]
Yup, this is just an artifact now -- I won't have time to fix this till the weekend, but yes, let's get rid of it

**Comment by jeromekelleher** [comment]
No hurry

**Comment by gtsambos** [comment]
The `path_ibd` thing has some relevance to the gene conversion ideas we have been floating around in Slack, but so much of the code base has changed in the last year or two that I think it's worth revisiting freshly when/if we need to.
