### ISSUE TITLE
ImportError: cannot import name '_unicodefun' from 'click'

### ISSUE THREAD

**Issue by szhan** [tskit-dev/tskit#2214]
I'm trying to push a commit. When I commit a staged change, I get the following error message:

```
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/Users/szhan/.cache/pre-commit/repotlp8vcj1/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/Users/szhan/.cache/pre-commit/repotlp8vcj1/py_env-python3/lib/python3.9/site-packages/black/__init__.py", line 6606, in patched_main
    patch_click()
  File "/Users/szhan/.cache/pre-commit/repotlp8vcj1/py_env-python3/lib/python3.9/site-packages/black/__init__.py", line 6595, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/Users/szhan/.cache/pre-commit/repotlp8vcj1/py_env-python3/lib/python3.9/site-packages/click/__init__.py)
```

It seems that it is a bug in ``black 22.3.0`` (https://github.com/psf/black/issues/2964) when using ``click==8.1.0``. I've tried to downgrade to ``click<=8.0.1`` and installed older versions of ``black``, but I'm still struggling with this issue. I'm not sure if anyone else is dealing with this! Also, I'm using ``python 3.9.0``. If you are _**not**_ encountering this problem, which version combination of ``python``, ``black``, and ``click`` are you using? Please let me know! Thanks!

**Comment by benjeffery** [comment]
That perticular issue was supposedly fixed in `black 22.3.0` which we are using. Your attempts to pin are likely failing as `pre-commit` uses its own isolated environment.
Everything is working for me with `Python v3.9.1`. Can you try `pre-commit clean` then `pre-commit run --all`?

**Comment by benjeffery** [comment]
To temporarily bypass this issue you can `git commit --no-verify`.

**Comment by szhan** [comment]
I restarted the terminal, and then it works with ``black 22.3.0 `` and ``click 8.1.0 ``. Ah, so silly!
